name: nisar-eval
channels:
  - conda-forge
  - defaults
dependencies:
  - rioxarray
  - geopandas
  - matplotlib
  - ipykernel
  - seaborn
  - netcdf4
  - h5py
  - autorift
  - pystac-client
  - odc-stac
  - planetary-computer
  - scipy
  - skimage